# -*- coding: utf-8 -*-
"""Loaded_model_RF_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K1BinMsDwsTNqF5cW1wizym4bJyi5vkJ
"""

import joblib
import pandas as pd
import numpy as np
from sklearn.metrics import (
    classification_report,
    balanced_accuracy_score,
    recall_score,
    precision_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)
import matplotlib.pyplot as plt
import seaborn as sns

# --- 1. ĐỊNH NGHĨA CLASS (Bắt buộc phải có để Joblib hiểu object là gì) ---
class ThresholdRFClassifier:
    def __init__(self, model, preprocessor, threshold=0.35):
        self.model = model
        self.preprocessor = preprocessor
        self.threshold = threshold
        self.feature_importances_ = model.feature_importances_

    def predict(self, X):
        X_prep = self.preprocessor.transform(X)
        proba = self.model.predict_proba(X_prep)[:, 1]
        return (proba >= self.threshold).astype(int)

    def predict_proba(self, X):
        X_prep = self.preprocessor.transform(X)
        return self.model.predict_proba(X_prep)

    def set_threshold(self, new_threshold):
        self.threshold = new_threshold
        print(f"✓ Threshold updated: {new_threshold:.2f}")

    def evaluate(self, X_test, y_test, show_confusion=True):
        y_pred = self.predict(X_test)
        y_proba = self.predict_proba(X_test)[:, 1]

        print("\n" + "="*60)
        print(" MODEL EVALUATION")
        print("="*60)
        print(f"Threshold: {self.threshold:.2f}")
        print(f"Balanced Accuracy: {balanced_accuracy_score(y_test, y_pred):.4f}")
        print(f"ROC-AUC:           {roc_auc_score(y_test, y_proba):.4f}")
        print("="*60)
        print(classification_report(y_test, y_pred))

        if show_confusion:
            cm = confusion_matrix(y_test, y_pred)
            plt.figure(figsize=(6, 5))
            sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
            plt.show()

    def get_feature_importance(self, top_n=10):
        # Hàm này cần file feature_importance.csv phải tồn tại
        try:
            importance_df = pd.read_csv('feature_importance.csv')
            print(importance_df.head(top_n))
        except:
            print(" Không tìm thấy file feature_importance.csv")

# --- 2. LOAD & CHẠY (Sửa phần tên file) ---

# Tải dữ liệu test từ file bạn đã upload
X_test_loaded = pd.read_csv('/content/drive/MyDrive/project ML cuối Kỳ/RF/X_test_cardio.csv') # import data ở đây
y_test_loaded = pd.read_csv('/content/drive/MyDrive/project ML cuối Kỳ/RF/y_test_cardio.csv').values.ravel()

try:
    # CÁCH 1: Load file wrapper (nếu bạn đã lưu file này từ trước)
    # Lưu ý tên file phải là 'rf_model_thresh0.35.pkl' như trong phần save của bạn
    loaded_model = joblib.load('/content/drive/MyDrive/project ML cuối Kỳ/RF/rf_model_thresh0.35.pkl') # import model ở đây
    print(" Đã load model wrapper thành công.")

    # Đánh giá
    loaded_model.evaluate(X_test_loaded, y_test_loaded)

except FileNotFoundError:
    print("Không tìm thấy file 'rf_model_thresh0.35.pkl'.")
    print("Hãy đảm bảo bạn đã chạy phần SAVE MODEL thành công trước.")

    # CÁCH 2: Tự dựng lại từ model gốc và preprocessor (nếu chỉ có 2 file này)
    try:
        print("\nĐang thử dựng lại từ 'rf_model.pkl' và 'preprocessor.pkl'...")
        rf = joblib.load('rf_model.pkl')
        prep = joblib.load('preprocessor.pkl')

        # Tái tạo lại object
        loaded_model = ThresholdRFClassifier(rf, prep, threshold=0.35)
        loaded_model.evaluate(X_test_loaded, y_test_loaded)
        print("Đã dựng lại và đánh giá thành công.")

    except FileNotFoundError:
        print("Cũng không tìm thấy 'rf_model.pkl' hoặc 'preprocessor.pkl'.")