# -*- coding: utf-8 -*-
"""Loaded_model_xgboost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U49sDeHQZfMs1TuP9sq2Wjr_UUao07cd
"""

import pandas as pd
import joblib
import matplotlib.pyplot as plt

from sklearn.metrics import (
    classification_report,
    balanced_accuracy_score,
    roc_auc_score,
    confusion_matrix,
    ConfusionMatrixDisplay
)


class ThresholdXGBClassifier:
    def __init__(self, model, preprocessor, threshold):
        self.model = model
        self.preprocessor = preprocessor
        self.threshold = threshold
        self.feature_importances_ = model.feature_importances_

    def predict(self, X):
        X_prep = self.preprocessor.transform(X)
        proba = self.model.predict_proba(X_prep)[:, 1]
        return (proba >= self.threshold).astype(int)

    def predict_proba(self, X):
        X_prep = self.preprocessor.transform(X)
        return self.model.predict_proba(X_prep)

    def set_threshold(self, new_threshold):
        self.threshold = new_threshold
        print(f"✓ Threshold updated to {new_threshold:.2f}")



model = joblib.load(
    "/content/drive/MyDrive/project ML cuối Kỳ/xgboost/xgb_model_thresh0.35.pkl"# import model
)
print(f"✓ Model loaded (threshold = {model.threshold:.2f})")



X_test = pd.read_csv(
    "/content/drive/MyDrive/project ML cuối Kỳ/xgboost/X_test_fe (1).csv" # import data
)
y_test = pd.read_csv(
    "/content/drive/MyDrive/project ML cuối Kỳ/xgboost/y_test (1).csv"
).values.ravel()

print(f"✓ Data loaded: X_test shape = {X_test.shape}")


y_pred = model.predict(X_test)

print("\n===== PERFORMANCE (Current Threshold) =====")
print(f"Balanced Accuracy: {balanced_accuracy_score(y_test, y_pred):.4f}")
print(f"ROC AUC: {roc_auc_score(y_test, y_pred):.4f}")
print(classification_report(
    y_test,
    y_pred,
    target_names=["No Disease", "Disease"]
))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["No Disease", "Disease"]
)

plt.figure(figsize=(5, 5))
disp.plot(cmap="Blues", values_format="d")
plt.title(f"Confusion Matrix (threshold = {model.threshold:.2f})")
plt.grid(False)
plt.show()

# Sensitivity & Specificity
tn, fp, fn, tp = cm.ravel()
sensitivity = tp / (tp + fn)
specificity = tn / (tn + fp)

print(f"Sensitivity (Recall – Disease): {sensitivity:.4f}")
print(f"Specificity (Recall – No Disease): {specificity:.4f}")


results = pd.DataFrame({
    "actual": y_test,
    "predicted": y_pred_new
})

results.to_csv("predictions.csv", index=False)
print("✓ Predictions saved to predictions.csv")