# -*- coding: utf-8 -*-
"""load_and_predict

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U63XPjL0pz5bnPctUO0aCfFg8Vl5oVkM
"""

import pandas as pd
import joblib

# ⚠️ PHẢI import class trước khi load model
from threshold_model import ThresholdLogisticClassifier

# ==============================
# 1. LOAD MODEL
# ==============================
MODEL_PATH = "logistic_model_thresh0.35.pkl"
model = joblib.load(MODEL_PATH)

print(f"✓ Model loaded (threshold = {model.threshold:.2f})")

# ==============================
# 2. LOAD DATA
# ==============================
DATA_PATH = "/content/data_base.csv"  # hoặc new_data.csv

if DATA_PATH.endswith(".csv"):
    X = pd.read_csv(DATA_PATH)
elif DATA_PATH.endswith(".xlsx"):
    X = pd.read_excel(DATA_PATH)
else:
    raise ValueError("Chỉ hỗ trợ file .csv hoặc .xlsx")

print("✓ Data loaded:", X.shape)

# ==============================
# 3. PREDICT
# ==============================
y_proba = model.predict_proba(X)[:, 1]
y_pred = model.predict(X)

# ==============================
# 4. MAP LABEL
# ==============================
label_map = {0: "Khỏe mạnh", 1: "Bệnh tim"}

result = X.copy()
result["Xac_suat_mac_benh"] = y_proba
result["Du_doan"] = pd.Series(y_pred).map(label_map)

# ==============================
# 5. SAVE RESULT
# ==============================
OUTPUT_PATH = "predictions_output.xlsx"
result.to_excel(OUTPUT_PATH, index=False)

print(f"✓ Prediction saved to {OUTPUT_PATH}")