# -*- coding: utf-8 -*-
"""threshold_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c4P274s8BI6GYumfhtOvH2gVV3hfL6HX
"""

import numpy as np

class ThresholdLogisticClassifier:
    """
    Logistic Regression với threshold tùy chỉnh
    """

    def __init__(self, pipeline, threshold=0.35):
        self.pipeline = pipeline
        self.threshold = threshold

    def predict_proba(self, X):
        return self.pipeline.predict_proba(X)

    def predict(self, X):
        proba = self.predict_proba(X)[:, 1]
        return (proba >= self.threshold).astype(int)

    def set_threshold(self, new_threshold):
        self.threshold = new_threshold